<?php

namespace ArchiflowWSFolder;

use ArchiflowWSFolder\Type;
use Phpro\SoapClient\Soap\ClassMap\ClassMapCollection;
use Phpro\SoapClient\Soap\ClassMap\ClassMap;

class ArchiFlowFolderClientClassmap
{

    public static function getCollection() : \Phpro\SoapClient\Soap\ClassMap\ClassMapCollection
    {
        return new ClassMapCollection([
            new ClassMap('ArrayOfguid', Type\ArrayOfguid::class),
            new ClassMap('ArrayOfint', Type\ArrayOfint::class),
            new ClassMap('ArrayOfstring', Type\ArrayOfstring::class),
            new ClassMap('LoggableBase', Type\LoggableBase::class),
            new ClassMap('UserRightsConfig', Type\UserRightsConfig::class),
            new ClassMap('CardOperationsFromList', Type\CardOperationsFromList::class),
            new ClassMap('ArrayOfGroup', Type\ArrayOfGroup::class),
            new ClassMap('Group', Type\Group::class),
            new ClassMap('GroupChart', Type\GroupChart::class),
            new ClassMap('Entity', Type\Entity::class),
            new ClassMap('ArrayOfUser', Type\ArrayOfUser::class),
            new ClassMap('User', Type\User::class),
            new ClassMap('Office', Type\Office::class),
            new ClassMap('ArrayOfOffice', Type\ArrayOfOffice::class),
            new ClassMap('ArrayOfUserRight', Type\ArrayOfUserRight::class),
            new ClassMap('UserRight', Type\UserRight::class),
            new ClassMap('ArrayOfOfficeChart', Type\ArrayOfOfficeChart::class),
            new ClassMap('OfficeChart', Type\OfficeChart::class),
            new ClassMap('SessionInfo', Type\SessionInfo::class),
            new ClassMap('BaseInput', Type\BaseInput::class),
            new ClassMap('BaseOutput', Type\BaseOutput::class),
            new ClassMap('TaskTemplate', Type\TaskTemplate::class),
            new ClassMap('ExternNotification', Type\ExternNotification::class),
            new ClassMap('ArrayOfExternNotificationOffice', Type\ArrayOfExternNotificationOffice::class),
            new ClassMap('ExternNotificationOffice', Type\ExternNotificationOffice::class),
            new ClassMap('ExternNotificationUsers', Type\ExternNotificationUsers::class),
            new ClassMap('InvoiceBase', Type\InvoiceBase::class),
            new ClassMap('MemberInfo', Type\MemberInfo::class),
            new ClassMap('SdiInfo', Type\SdiInfo::class),
            new ClassMap('InvoiceIn', Type\InvoiceIn::class),
            new ClassMap('InvoiceOut', Type\InvoiceOut::class),
            new ClassMap('Color', Type\Color::class),
            new ClassMap('SendObject', Type\SendObject::class),
            new ClassMap('ArrayOfSendEntity', Type\ArrayOfSendEntity::class),
            new ClassMap('SendEntity', Type\SendEntity::class),
            new ClassMap('SendOptions', Type\SendOptions::class),
            new ClassMap('ArrayOfCard', Type\ArrayOfCard::class),
            new ClassMap('Card', Type\Card::class),
            new ClassMap('ArrayOfAdditive', Type\ArrayOfAdditive::class),
            new ClassMap('Additive', Type\Additive::class),
            new ClassMap('CardExpirationInfo', Type\CardExpirationInfo::class),
            new ClassMap('CardHasData', Type\CardHasData::class),
            new ClassMap('ArrayOfField', Type\ArrayOfField::class),
            new ClassMap('Field', Type\Field::class),
            new ClassMap('Annotation', Type\Annotation::class),
            new ClassMap('Folder', Type\Folder::class),
            new ClassMap('ArrayOfDrawer', Type\ArrayOfDrawer::class),
            new ClassMap('Drawer', Type\Drawer::class),
            new ClassMap('Cabinet', Type\Cabinet::class),
            new ClassMap('ArrayOfFolder', Type\ArrayOfFolder::class),
            new ClassMap('ArrayOfCabinet', Type\ArrayOfCabinet::class),
            new ClassMap('SetCardsFoldersInput', Type\SetCardsFoldersInput::class),
            new ClassMap('SetCardsFoldersOutput', Type\SetCardsFoldersOutput::class),
            new ClassMap('GetCardsInFolderInput', Type\GetCardsInFolderInput::class),
            new ClassMap('GetCardsInFolderOutput', Type\GetCardsInFolderOutput::class),
            new ClassMap('SearchFoldersByParamInput', Type\SearchFoldersByParamInput::class),
            new ClassMap('SearchFoldersByParamOutput', Type\SearchFoldersByParamOutput::class),
            new ClassMap('SendFolderInput', Type\SendFolderInput::class),
            new ClassMap('SendFolderOutput', Type\SendFolderOutput::class),
            new ClassMap('GetFolder', Type\GetFolder::class),
            new ClassMap('GetFolderResponse', Type\GetFolderResponse::class),
            new ClassMap('GetFolders', Type\GetFolders::class),
            new ClassMap('GetFoldersResponse', Type\GetFoldersResponse::class),
            new ClassMap('SearchFolders', Type\SearchFolders::class),
            new ClassMap('SearchFoldersResponse', Type\SearchFoldersResponse::class),
            new ClassMap('GetFolderVisibility', Type\GetFolderVisibility::class),
            new ClassMap('GetFolderVisibilityResponse', Type\GetFolderVisibilityResponse::class),
            new ClassMap('InsertFolder', Type\InsertFolder::class),
            new ClassMap('InsertFolderResponse', Type\InsertFolderResponse::class),
            new ClassMap('AddFolderInDrawer', Type\AddFolderInDrawer::class),
            new ClassMap('AddFolderInDrawerResponse', Type\AddFolderInDrawerResponse::class),
            new ClassMap('SendFolder', Type\SendFolder::class),
            new ClassMap('SendFolderResponse', Type\SendFolderResponse::class),
            new ClassMap('ModifyFolder', Type\ModifyFolder::class),
            new ClassMap('ModifyFolderResponse', Type\ModifyFolderResponse::class),
            new ClassMap('DeleteFolder', Type\DeleteFolder::class),
            new ClassMap('DeleteFolderResponse', Type\DeleteFolderResponse::class),
            new ClassMap('GetDrawers', Type\GetDrawers::class),
            new ClassMap('GetDrawersResponse', Type\GetDrawersResponse::class),
            new ClassMap('GetDrawerVisibility', Type\GetDrawerVisibility::class),
            new ClassMap('GetDrawerVisibilityResponse', Type\GetDrawerVisibilityResponse::class),
            new ClassMap('InsertDrawer', Type\InsertDrawer::class),
            new ClassMap('InsertDrawerResponse', Type\InsertDrawerResponse::class),
            new ClassMap('ModifyDrawer', Type\ModifyDrawer::class),
            new ClassMap('ModifyDrawerResponse', Type\ModifyDrawerResponse::class),
            new ClassMap('DeleteDrawer', Type\DeleteDrawer::class),
            new ClassMap('DeleteDrawerResponse', Type\DeleteDrawerResponse::class),
            new ClassMap('GetCabinets', Type\GetCabinets::class),
            new ClassMap('GetCabinetsResponse', Type\GetCabinetsResponse::class),
            new ClassMap('GetCabinetVisibility', Type\GetCabinetVisibility::class),
            new ClassMap('GetCabinetVisibilityResponse', Type\GetCabinetVisibilityResponse::class),
            new ClassMap('InsertCabinet', Type\InsertCabinet::class),
            new ClassMap('InsertCabinetResponse', Type\InsertCabinetResponse::class),
            new ClassMap('ModifyCabinet', Type\ModifyCabinet::class),
            new ClassMap('ModifyCabinetResponse', Type\ModifyCabinetResponse::class),
            new ClassMap('DeleteCabinet', Type\DeleteCabinet::class),
            new ClassMap('DeleteCabinetResponse', Type\DeleteCabinetResponse::class),
            new ClassMap('AddCardInFolder', Type\AddCardInFolder::class),
            new ClassMap('AddCardInFolderResponse', Type\AddCardInFolderResponse::class),
            new ClassMap('RemoveCardFromFolder', Type\RemoveCardFromFolder::class),
            new ClassMap('RemoveCardFromFolderResponse', Type\RemoveCardFromFolderResponse::class),
            new ClassMap('SetCardsFolders', Type\SetCardsFolders::class),
            new ClassMap('SetCardsFoldersResponse', Type\SetCardsFoldersResponse::class),
            new ClassMap('GetCardsInFolder', Type\GetCardsInFolder::class),
            new ClassMap('GetCardsInFolderResponse', Type\GetCardsInFolderResponse::class),
            new ClassMap('SearchFoldersByParam', Type\SearchFoldersByParam::class),
            new ClassMap('SearchFoldersByParamResponse', Type\SearchFoldersByParamResponse::class),
            new ClassMap('SendFolderByParam', Type\SendFolderByParam::class),
            new ClassMap('SendFolderByParamResponse', Type\SendFolderByParamResponse::class),
            new ClassMap('InvalidSessionFault', Type\InvalidSessionFault::class),
            new ClassMap('BaseFault', Type\BaseFault::class),
            new ClassMap('ParamValidationFault', Type\ParamValidationFault::class),
            new ClassMap('NoRightsFault', Type\NoRightsFault::class),
            new ClassMap('VisibilityFault', Type\VisibilityFault::class),
            new ClassMap('ArchiflowServiceExceptionDetail', Type\ArchiflowServiceExceptionDetail::class),
        ]);
    }


}

