<?php 

/* Linguaggio */
//$language = "it";

/* Gestione contenuti testuali */
$login['label']['titolo'] = ".:: ".$_SERVER['HTTP_HOST']." - Login ::.";

$login['label']['username']['it'] = "Nome utente";
$login['label']['password']['it'] = "Parola chiave";
$login['label']['siss']['it'] = "Sistemi Informativi e Servizi per la Sanit&agrave;";
$login['label']['reserved']['it'] = "Tutti i diritti riservati";
$login['label']['login-button']['it'] = "Accedi";
$login['label']['cancel-button']['it'] = "Cancella";
$login['label']['lost-password']['it'] = "Recupero Password ?";

$login['label']['username']['en'] = "Username";
$login['label']['password']['en'] = "Password";
$login['label']['siss']['en'] = "System and Services for Health";
$login['label']['reserved']['en'] = "All rights reserved";
$login['label']['login-button']['en'] = "Login";
$login['label']['cancel-button']['en'] = "Cancel";
$login['label']['lost-password']['en'] = "Lost Password ?";

/* Errore credenziali */
$login['label']['login-error']['it'] = "Nome utente o password errati";
$login['label']['login-error']['en'] = "Wrong Userid or Password";

/* Caricamento servizio */
$login['label']['login-loading']['it'] = "Caricamento in corso ...";
$login['label']['login-loading']['en'] = "Loading ...";

/*** Captcha ***/
$login['label']['captcha']['it'] = "Codice di sicurezza";
$login['label']['captcha']['en'] = "Security code";
$login['captcha']['enabled'] = false;
$login['captcha']['number_of_tries_before_captcha'] = 3;
/* Errore credenziali Captcha*/
$login['label']['login-error-captcha']['it'] = "Codice di sicurezza errato";
$login['label']['login-error-captcha']['en'] = "Wrong security code";


?>
