<?php 

/* Linguaggio */
//$language = "en";

/* Gestione contenuti testuali */
$lost_user['label']['titolo'] = ".:: ".$_SERVER['HTTP_HOST']." - {$lost_user['label']['recovery-pass'][$language]} ::.";

$lost_user['label']['userid']['it'] = "ID Utente";
$lost_user['label']['recovery-pass']['it'] = "Recupero Userid";
$lost_user['label']['siss']['it'] = "Sistemi Informativi e Servizi per la Sanit&agrave;";
$lost_user['label']['reserved']['it'] = "Tutti i diritti riservati";
$lost_user['label']['proceed-button']['it'] = "Procedi";
$lost_user['label']['lost-userid']['it'] = "Recupero Nome utente?";
$lost_user['label']['Errore richiesta sospesa']['it']="Userid non presente in banca dati o una precedente richiesta di cambio password  è ancora sospesa";
$lost_user['label']['Titolo Forget Userid']['it']="Procedere con l'inserimento della sua e-mail.";
$lost_user['label']['Invia']['it']="Invia";
$lost_user['label']['Regole']['it']="REGOLE";
$lost_user['label']['Regola1']['it']="Dopo l'invio della richiesta verra' inviato all'indirizzo e-mail l'userid corrispondente in banca dati ";
$lost_user['label']['Richiesta effettuata']['it']="Richiesta effettuata";
$lost_user['label']['Oggetto mail']['it']="Assistenza Userid Cineca ";
$lost_user['label']['Userid smarrito in']['it']="Userid smarrito in";
$lost_user['label']['Il suo userid è']['it']="Il suo userid è";
$lost_user['label']['Nessuna e-mail inserita']['it']="Nessuna e-mail inserita";
$lost_user['label']['Nessun userid inserito']['it']="Nessun userid in banca dati corrisponde alla mail indicata";
$lost_user['label']['Titolo']=".:: ".$_SERVER['HTTP_HOST']." - Recupero userid  ::.";
$lost_user['label']['Userid']['it']="Nome Utente";
$lost_user['label']['Siss']['it']="Sistemi Informativi e Servizi per la Sanit&agrave;";
$lost_user['label']['Reserved']['it']="Tutti i diritti riservati";
$lost_user['label']['backtohome']['it']="Torna alla Home Page";


$lost_user['label']['userid']['en'] = "Userid";
$lost_user['label']['recovery-pass']['en'] = "Userid Recovery";
$lost_user['label']['siss']['en'] = "System and Services for Health";
$lost_user['label']['reserved']['en'] = "All rights reserved";
$lost_user['label']['proceed-button']['en'] = "Login";
$lost_user['label']['lost-userid']['en'] = "Lost Userid?";
$lost_user['label']['Errore richiesta sospesa']['en']="Userid not recognized or  previous request  still pending";
$lost_user['label']['Titolo Forget Userid']['en']="Please enter your e-mail address";
$lost_user['label']['Invia']['en']="Send";
$lost_user['label']['Regole']['en']="RULES";
$lost_user['label']['Regola1']['en']="Your userid will be sent to the entered e-mail address ";
$lost_user['label']['Richiesta effettuata']['en']="Request done";
$lost_user['label']['Oggetto mail']['en']="Cineca Userid Assistance";
$lost_user['label']['Userid smarrito in']['en']="Userid lost in";
$lost_user['label']['Il suo userid è']['en']="Your userid is";
$lost_user['label']['Nessuna e-mail inserita']['en']="No e-mail address entered";
$lost_user['label']['Nessun userid inserito']['en']="No userid  corrisponding to the entered e-mail address ";
$lost_user['label']['Titolo']=".:: ".$_SERVER['HTTP_HOST']." - Userid recovery ::.";
$lost_user['label']['Userid']['en']="Userid";
$lost_user['label']['Siss']['en']="System and Services for Health";
$lost_user['label']['Reserved']['en']="All rights reserved";
$lost_user['label']['backtohome']['en']="Go to Home Page";

?>
