<?php

$messages['__welcome_login_message__']="Inserire username e password per accedere al sistema";
$messages['__username__']='Username';
$messages['__password__']='Password';
$messages['__login_button_label__']='Accedi';
$messages['__forgot_password__']='Password dimenticata?';
$messages['__forgot_username__']='Username dimenticata?';
$messages['__error_message__']='Username o password errate';
$messages['__title_page__']="SSO Login";
$messages['__processing__']="Accesso in corso";
