<?php

$messages['__welcome_login_message__']="Fill in username and password to login";
$messages['__username__']='Username';
$messages['__password__']='Password';
$messages['__login_button_label__']='Enter';
$messages['__forgot_password__']='Password recovery';
$messages['__forgot_username__']='Username recovery';
$messages['__error_message__']='Wrong username or password';
$messages['__title_page__']="SSO Login";
$messages['__processing__']="Logging in";
