<?php

namespace IrideWS;

use IrideWS\Type;
use Phpro\SoapClient\Soap\ClassMap\ClassMapCollection;
use Phpro\SoapClient\Soap\ClassMap\ClassMap;

class IrideWSClassmap
{

    public static function getCollection() : \Phpro\SoapClient\Soap\ClassMap\ClassMapCollection
    {
        return new ClassMapCollection([
            new ClassMap('LeggiProtocollo', Type\LeggiProtocollo::class),
            new ClassMap('LeggiProtocolloResponse', Type\LeggiProtocolloResponse::class),
            new ClassMap('MittenteDestinatarioOut', Type\MittenteDestinatarioOut::class),
            new ClassMap('ArrayOfMittenteDestinatarioOut', Type\ArrayOfMittenteDestinatarioOut::class),
            new ClassMap('AllegatoOut', Type\AllegatoOut::class),
            new ClassMap('ArrayOfAllegatoOut', Type\ArrayOfAllegatoOut::class),
            new ClassMap('ImpegnoOut', Type\ImpegnoOut::class),
            new ClassMap('ArrayOfImpegnoOut', Type\ArrayOfImpegnoOut::class),
            new ClassMap('AccertamentoOut', Type\AccertamentoOut::class),
            new ClassMap('ArrayOfAccertamentoOut', Type\ArrayOfAccertamentoOut::class),
            new ClassMap('CentriDiCostoOut', Type\CentriDiCostoOut::class),
            new ClassMap('ArrayOfCentriDiCostoOut', Type\ArrayOfCentriDiCostoOut::class),
            new ClassMap('RegistroAssegnatoOut', Type\RegistroAssegnatoOut::class),
            new ClassMap('ArrayOfRegistroAssegnatoOut', Type\ArrayOfRegistroAssegnatoOut::class),
            new ClassMap('InteropOut', Type\InteropOut::class),
            new ClassMap('RispostaAlProtocolloOut', Type\RispostaAlProtocolloOut::class),
            new ClassMap('ProtocolloGeneratoOut', Type\ProtocolloGeneratoOut::class),
            new ClassMap('ArrayOfProtocolloGeneratoOut', Type\ArrayOfProtocolloGeneratoOut::class),
            new ClassMap('CorrispondenteOut', Type\CorrispondenteOut::class),
            new ClassMap('ArrayOfCorrispondenteOut', Type\ArrayOfCorrispondenteOut::class),
            new ClassMap('CampoUtente', Type\CampoUtente::class),
            new ClassMap('ArrayOfCampoUtente', Type\ArrayOfCampoUtente::class),
            new ClassMap('RecordUtente', Type\RecordUtente::class),
            new ClassMap('ArrayOfRecordUtente', Type\ArrayOfRecordUtente::class),
            new ClassMap('TabellaUtente', Type\TabellaUtente::class),
            new ClassMap('ArrayOfTabellaUtente', Type\ArrayOfTabellaUtente::class),
            new ClassMap('DocumentoOut', Type\DocumentoOut::class),
            new ClassMap('LeggiDocumento', Type\LeggiDocumento::class),
            new ClassMap('LeggiDocumentoResponse', Type\LeggiDocumentoResponse::class),
            new ClassMap('InserisciProtocolloEAnagrafiche', Type\InserisciProtocolloEAnagrafiche::class),
            new ClassMap('RecapitoIn', Type\RecapitoIn::class),
            new ClassMap('ArrayOfRecapitoIn', Type\ArrayOfRecapitoIn::class),
            new ClassMap('MittenteDestinatarioIn', Type\MittenteDestinatarioIn::class),
            new ClassMap('ArrayOfMittenteDestinatarioIn', Type\ArrayOfMittenteDestinatarioIn::class),
            new ClassMap('AllegatoIn', Type\AllegatoIn::class),
            new ClassMap('ArrayOfAllegatoIn', Type\ArrayOfAllegatoIn::class),
            new ClassMap('ProtocolloIn', Type\ProtocolloIn::class),
            new ClassMap('InserisciProtocolloEAnagraficheResponse', Type\InserisciProtocolloEAnagraficheResponse::class),
            new ClassMap('RegistroOut', Type\RegistroOut::class),
            new ClassMap('ArrayOfRegistroOut', Type\ArrayOfRegistroOut::class),
            new ClassMap('AllegatoInseritoOut', Type\AllegatoInseritoOut::class),
            new ClassMap('ArrayOfAllegatoInseritoOut', Type\ArrayOfAllegatoInseritoOut::class),
            new ClassMap('ProtocolloOut', Type\ProtocolloOut::class),
            new ClassMap('InserisciDocumentoEAnagrafiche', Type\InserisciDocumentoEAnagrafiche::class),
            new ClassMap('InserisciDocumentoEAnagraficheResponse', Type\InserisciDocumentoEAnagraficheResponse::class),
            new ClassMap('AggiungiAllegati', Type\AggiungiAllegati::class),
            new ClassMap('NuoviAllegati', Type\NuoviAllegati::class),
            new ClassMap('AggiungiAllegatiResponse', Type\AggiungiAllegatiResponse::class),
            new ClassMap('LeggiProtocolloMultiDB', Type\LeggiProtocolloMultiDB::class),
            new ClassMap('LeggiProtocolloMultiDBResponse', Type\LeggiProtocolloMultiDBResponse::class),
            new ClassMap('LeggiDocumentoMultiDB', Type\LeggiDocumentoMultiDB::class),
            new ClassMap('LeggiDocumentoMultiDBResponse', Type\LeggiDocumentoMultiDBResponse::class),
            new ClassMap('InserisciProtocolloEAnagraficheMultiDB', Type\InserisciProtocolloEAnagraficheMultiDB::class),
            new ClassMap('InserisciProtocolloEAnagraficheMultiDBResponse', Type\InserisciProtocolloEAnagraficheMultiDBResponse::class),
            new ClassMap('InserisciDocumentoEAnagraficheMultiDB', Type\InserisciDocumentoEAnagraficheMultiDB::class),
            new ClassMap('InserisciDocumentoEAnagraficheMultiDBResponse', Type\InserisciDocumentoEAnagraficheMultiDBResponse::class),
            new ClassMap('AggiungiAllegatiMultiDB', Type\AggiungiAllegatiMultiDB::class),
            new ClassMap('AggiungiAllegatiMultiDBResponse', Type\AggiungiAllegatiMultiDBResponse::class),
            new ClassMap('Login', Type\Login::class),
            new ClassMap('LoginResponse', Type\LoginResponse::class),
            new ClassMap('LoginOut', Type\LoginOut::class),
            new ClassMap('LoginMultiDB', Type\LoginMultiDB::class),
            new ClassMap('LoginMultiDBResponse', Type\LoginMultiDBResponse::class),
            new ClassMap('RicercaAmministrazione', Type\RicercaAmministrazione::class),
            new ClassMap('RicercaAmministrazioneResponse', Type\RicercaAmministrazioneResponse::class),
            new ClassMap('RicercaAmministrazioneMultiDB', Type\RicercaAmministrazioneMultiDB::class),
            new ClassMap('RicercaAmministrazioneMultiDBResponse', Type\RicercaAmministrazioneMultiDBResponse::class),
            new ClassMap('AggiungiAllegati2', Type\AggiungiAllegati2::class),
            new ClassMap('AggiungiAllegati2Response', Type\AggiungiAllegati2Response::class),
            new ClassMap('AllegatiInseritiOut', Type\AllegatiInseritiOut::class),
            new ClassMap('InserisciDocumentoDaDM', Type\InserisciDocumentoDaDM::class),
            new ClassMap('DocumentumIn', Type\DocumentumIn::class),
            new ClassMap('InserisciDocumentoDaDMResponse', Type\InserisciDocumentoDaDMResponse::class),
            new ClassMap('DocumentumOut', Type\DocumentumOut::class),
            new ClassMap('ModificaDocumentoEAnagrafiche', Type\ModificaDocumentoEAnagrafiche::class),
            new ClassMap('ModificaProtocolloIn', Type\ModificaProtocolloIn::class),
            new ClassMap('ModificaDocumentoEAnagraficheResponse', Type\ModificaDocumentoEAnagraficheResponse::class),
            new ClassMap('ModificaProtocolloOut', Type\ModificaProtocolloOut::class),
            new ClassMap('CreaCopie', Type\CreaCopie::class),
            new ClassMap('UODestinataria', Type\UODestinataria::class),
            new ClassMap('ArrayOfUODestinataria', Type\ArrayOfUODestinataria::class),
            new ClassMap('CreaCopieIn', Type\CreaCopieIn::class),
            new ClassMap('CreaCopieResponse', Type\CreaCopieResponse::class),
            new ClassMap('CopiaCreata', Type\CopiaCreata::class),
            new ClassMap('ArrayOfCopiaCreata', Type\ArrayOfCopiaCreata::class),
            new ClassMap('CreaCopieOut', Type\CreaCopieOut::class),
            new ClassMap('LeggiBarcode', Type\LeggiBarcode::class),
            new ClassMap('LeggiBarcodeResponse', Type\LeggiBarcodeResponse::class),
            new ClassMap('LeggiDocumentoString', Type\LeggiDocumentoString::class),
            new ClassMap('LeggiDocumentoStringResponse', Type\LeggiDocumentoStringResponse::class),
            new ClassMap('LeggiProtocolloString', Type\LeggiProtocolloString::class),
            new ClassMap('LeggiProtocolloStringResponse', Type\LeggiProtocolloStringResponse::class),
            new ClassMap('LeggiBarcodeString', Type\LeggiBarcodeString::class),
            new ClassMap('LeggiBarcodeStringResponse', Type\LeggiBarcodeStringResponse::class),
            new ClassMap('InserisciDocumentoEAnagraficheString', Type\InserisciDocumentoEAnagraficheString::class),
            new ClassMap('InserisciDocumentoEAnagraficheStringResponse', Type\InserisciDocumentoEAnagraficheStringResponse::class),
            new ClassMap('InserisciProtocolloEAnagraficheString', Type\InserisciProtocolloEAnagraficheString::class),
            new ClassMap('InserisciProtocolloEAnagraficheStringResponse', Type\InserisciProtocolloEAnagraficheStringResponse::class),
            new ClassMap('ModificaDocumentoEAnagraficheString', Type\ModificaDocumentoEAnagraficheString::class),
            new ClassMap('ModificaDocumentoEAnagraficheStringResponse', Type\ModificaDocumentoEAnagraficheStringResponse::class),
            new ClassMap('RicercaPerCodiceFiscaleString', Type\RicercaPerCodiceFiscaleString::class),
            new ClassMap('RicercaPerCodiceFiscaleStringResponse', Type\RicercaPerCodiceFiscaleStringResponse::class),
            new ClassMap('AggiungiAllegatiString', Type\AggiungiAllegatiString::class),
            new ClassMap('AggiungiAllegatiStringResponse', Type\AggiungiAllegatiStringResponse::class),
            new ClassMap('CreaCopieString', Type\CreaCopieString::class),
            new ClassMap('CreaCopieStringResponse', Type\CreaCopieStringResponse::class),
            new ClassMap('PubblicazioneDocumento', Type\PubblicazioneDocumento::class),
            new ClassMap('PubblicazioneDocumentoResponse', Type\PubblicazioneDocumentoResponse::class),
            new ClassMap('LeggiAnagrafica', Type\LeggiAnagrafica::class),
            new ClassMap('LeggiAnagraficaResponse', Type\LeggiAnagraficaResponse::class),
            new ClassMap('LeggiCopie', Type\LeggiCopie::class),
            new ClassMap('LeggiCopieResponse', Type\LeggiCopieResponse::class),
            new ClassMap('EliminaAllegato', Type\EliminaAllegato::class),
            new ClassMap('EliminaAllegatoResponse', Type\EliminaAllegatoResponse::class),
            new ClassMap('AnnullaDocumento', Type\AnnullaDocumento::class),
            new ClassMap('AnnullaDocumentoResponse', Type\AnnullaDocumentoResponse::class),
            new ClassMap('CollegaDocumento', Type\CollegaDocumento::class),
            new ClassMap('CollegaDocumentoResponse', Type\CollegaDocumentoResponse::class),
            new ClassMap('LeggiDocumentoPlus', Type\LeggiDocumentoPlus::class),
            new ClassMap('LeggiDocumentoPlusResponse', Type\LeggiDocumentoPlusResponse::class),
            new ClassMap('InserisciDatiUtente', Type\InserisciDatiUtente::class),
            new ClassMap('InserisciDatiUtenteResponse', Type\InserisciDatiUtenteResponse::class),
            new ClassMap('EsitoOperazione', Type\EsitoOperazione::class),
            new ClassMap('RicercaPerCodiceFiscale', Type\RicercaPerCodiceFiscale::class),
            new ClassMap('RicercaPerCodiceFiscaleResponse', Type\RicercaPerCodiceFiscaleResponse::class),
            new ClassMap('ProtocolloSoggettoOut', Type\ProtocolloSoggettoOut::class),
            new ClassMap('ArrayOfProtocolloSoggettoOut', Type\ArrayOfProtocolloSoggettoOut::class),
            new ClassMap('ProtocolliSoggettoOut', Type\ProtocolliSoggettoOut::class),
            new ClassMap('RicercaPerCodiceFiscaleMultiDB', Type\RicercaPerCodiceFiscaleMultiDB::class),
            new ClassMap('RicercaPerCodiceFiscaleMultiDBResponse', Type\RicercaPerCodiceFiscaleMultiDBResponse::class),
        ]);
    }


}

