alter table DOC_MD_FIELD add DELETED number(1,0);

update DOC_MD_FIELD set deleted=0;

alter table DOC_MD_TEMPLATE add DELETED number(1,0);

update doc_md_template set deleted=0;

ALTER TABLE DOC_TYPE_WF
MODIFY (PROCESS_KEY NOT NULL);

ALTER TABLE DOC_TYPE_WF
MODIFY (TYPE_ID NOT NULL);

ALTER TABLE DOC_TYPE_MD_TEMPLATE
MODIFY (TEMPLATE_ID NOT NULL);

ALTER TABLE DOC_TYPE_MD_TEMPLATE
MODIFY (TYPE_ID NOT NULL);

ALTER TABLE DOC_MD_FIELD
MODIFY (TEMPLATE_ID NOT NULL);

ALTER TABLE DOC_TPL_ACL_CONTAINER
MODIFY (ACL_ID NOT NULL);

ALTER TABLE DOC_ACL_CONTAINER
MODIFY (ACL_DI NOT NULL);
